language: php

php:
  - 5.4

before_script: 
    - sudo apt-get install memcached
    - echo "no" | pecl install --force memcache
    - echo "extension=\"memcache.so\"" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer install --dev

script: php bin/tests.php
