language: php

php:
  - 5.4

services:
  - memcached

before_script: 
  - sudo sh -c "echo "extension=\"memcache.so\"" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`"
  - composer install --dev

script: php bin/tests.php
