language: php

php:
  - 5.4

before_script: 
    - sudo apt-get install memcached
    - sudo apt-get install php5-memcache
    - env php -m
    - find /etc/php5
    - composer install --dev

script: php bin/tests.php
